site_name: Programação Orientada a Objeto
site_description: Lista de exercícios da disciplina de Programação Orientada a Objeto do curso de Analise e Desenvolvimento de Sistemas da FATEC de Franca.
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
google_analytics: ['UA-70830801-9', 'auto']
repo_url: https://github.com/getuliovinicius/programacao.orientada.objeto
repo_name: GitHub
edit_uri: blob/master/docs/mds/
remote_branch: gh-pages
remote_name: origin
docs_dir: 'mds'
pages:
  - Inicio: index.md
  - Lista de exercícios 1: lista-1.md
  - Lista de exercícios 2: lista-2.md
  - Lista de exercícios 3: lista-3.md
  #- Lista de exercícios 4: lista-4.md
  #- Lista de exercícios 5: lista-5.md
theme: readthedocs
extra:
  version: 1.0
markdown_extensions:
  - smarty
  - nl2br
  - admonition
  - codehilite
  - sane_lists
  - toc:
    permalink: True
    separator: "_"
  - footnotes
